default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: postgres_db
  port: 5432

development:
  <<: *default
  database: gender-gap-db

test:
  <<: *default
  database: gender-gap-db-test

production:
  <<: *default
  database: gender-gap-db-prod