
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: db

development:
  <<: *default
  database: gender_gap_development

test:
  <<: *default
  database: gender_gap_test

production:
  <<: *default
  database: gender_gap_production
  host: db
  username: user
  password: <%= ENV['POSTGRES_PASSWORD'] %>
