
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

  username: postgres
  password: password
  host: postgres_db

development:
  <<: *default
  database: gender-gap-db

test:
  <<: *default

production:
  <<: *default