default: &default
adapter: postgresql
encoding: unicode
host: localhost
username: horse_racing_dev_user
password: your_password
database: horse_racing_dev
pool: 5

development:
  <<: *default



production:
  <<: *default
  database: horse-racing-app