default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: myuser
  password: mypassword
  database: mydatabase
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_HOST'] %>
development:
  <<: *default
