default: &default
  adapter: postgresql
  encoding: unicode
  host: horse-racing-db-02.cx0oukwwi4qa.ap-northeast-1.rds.amazonaws.com
  username: horse-racing-app
  password: Koki245836!
  database: postgres
  pool: 5

development:
  <<: *default

production:
  <<: *default
  database: horse-racing-app