default: &default
  adapter: postgresql
  encoding: unicode
  host: horse-racing-db-02.cx0oukwwi4qa.ap-northeast-1.rds.amazonaws.com
  username: admin_user
  password: Koki245836!
  database: postgres
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_HOST'] %>
development:
  <<: *default
