default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  database: horse-racing-app
  pool: 5

development:
  <<: *default

production:
  <<: *default
  database: horse-racing-app